### ISSUE TITLE
How can we show pre selected items?

### ISSUE THREAD

**Issue by abdulwahid24** [thepolyglots/flutter_multi_chip_select#2]
Hi,

I highly appreciate your work and would like to know if we can have preselected items while loading the screen.
This is needed to show in edit form screen.

Please do let me know your thoughts.

Thanks

**Comment by abhinav-jha-dev** [comment]
Thanks, @abdulwahid24 , I think its something that needs fixing. So moving this issue to development.

**Comment by abhinav-jha-dev** [comment]
Hi @abdulwahid24 ,
This issue is resolved and the package is updated to new version 0.1.1. Please use the latest package version.

Feel free to experiment and create a new issue if you find one.

Thanks & have a great day!
